import { PERMISSIONS } from "./permissions";


// Why are we separating this?
// Notice we have two files now:
// permissions.js
// contains all available permissions.
// rolePermissions.js
// contains which role gets which permissions.
export const ROLE_PERMISSIONS = {
  ROLE_SUPER_ADMIN: ["*"],

  ROLE_ADMIN: [
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.STUDENT_VIEW,
    PERMISSIONS.STUDENT_CREATE,
    PERMISSIONS.STUDENT_EDIT,
    PERMISSIONS.STUDENT_DELETE,

    PERMISSIONS.TEACHER_VIEW,
    PERMISSIONS.TEACHER_CREATE,
    PERMISSIONS.TEACHER_EDIT,
    PERMISSIONS.TEACHER_DELETE,

    PERMISSIONS.HOMEWORK_VIEW,
    PERMISSIONS.HOMEWORK_CREATE,
    PERMISSIONS.HOMEWORK_EDIT,
    PERMISSIONS.HOMEWORK_DELETE,

    PERMISSIONS.NOTICE_VIEW,
    PERMISSIONS.NOTICE_CREATE,
    PERMISSIONS.NOTICE_EDIT,
    PERMISSIONS.NOTICE_DELETE,

    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.SETTINGS_EDIT,
  ],

  ROLE_TEACHER: [
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.HOMEWORK_VIEW,
    PERMISSIONS.HOMEWORK_CREATE,
    PERMISSIONS.HOMEWORK_EDIT,

    PERMISSIONS.NOTICE_VIEW,

    PERMISSIONS.STUDENT_VIEW,
  ],

  ROLE_STUDENT: [
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.HOMEWORK_VIEW,

    PERMISSIONS.NOTICE_VIEW,
  ],
};