import { ROLES } from "@/app/constants";

import {
    DASHBOARD_PERMISSIONS,
    STUDENT_PERMISSIONS,
    TEACHER_PERMISSIONS,
    HOMEWORK_PERMISSIONS,
    NOTICE_PERMISSIONS,
    SETTINGS_PERMISSIONS,
} from "@/features/auth/permissions";

export const ROLE_PERMISSIONS = {
    [ROLES.SUPER_ADMIN]: ["*"],

    [ROLES.TEACHER]: [
        DASHBOARD_PERMISSIONS.VIEW,

        STUDENT_PERMISSIONS.VIEW,

        TEACHER_PERMISSIONS.VIEW,

        HOMEWORK_PERMISSIONS.VIEW,
        HOMEWORK_PERMISSIONS.CREATE,
        HOMEWORK_PERMISSIONS.EDIT,

        NOTICE_PERMISSIONS.VIEW,
        NOTICE_PERMISSIONS.CREATE,
        NOTICE_PERMISSIONS.EDIT,

        SETTINGS_PERMISSIONS.VIEW,

    ],
};