const MOCK_USERS = [
    {
        id: "1",
        name: "Rahul Kumar",
        email: "rahul@example.com",
        phone: "+91 98765 43210",
        role: "Institute Admin",
        department: "Administration",
        status: "Active",
    },
    {
        id: "2",
        name: "Amit Singh",
        email: "amit@example.com",
        phone: "+91 87654 32109",
        role: "Teacher",
        department: "Science",
        status: "Active",
    },
    {
        id: "3",
        name: "Priya Sharma",
        email: "priya@example.com",
        phone: "+91 76543 21098",
        role: "Student",
        department: "Mathematics",
        status: "Active",
    },
    {
        id: "4",
        name: "Sneha Patel",
        email: "sneha@example.com",
        phone: "+91 65432 10987",
        role: "Teacher",
        department: "English",
        status: "Inactive",
    },
    {
        id: "5",
        name: "Vikram Joshi",
        email: "vikram@example.com",
        phone: "+91 54321 09876",
        role: "Student",
        department: "Physics",
        status: "Active",
    },
    {
        id: "6",
        name: "Anjali Mehta",
        email: "anjali@example.com",
        phone: "+91 43210 98765",
        role: "Institute Admin",
        department: "Administration",
        status: "Active",
    },
    {
        id: "7",
        name: "Rohan Das",
        email: "rohan@example.com",
        phone: "+91 32109 87654",
        role: "Student",
        department: "Chemistry",
        status: "Inactive",
    },
    {
        id: "8",
        name: "Kavya Reddy",
        email: "kavya@example.com",
        phone: "+91 21098 76543",
        role: "Teacher",
        department: "Biology",
        status: "Active",
    },
    {
        id: "9",
        name: "Arjun Nair",
        email: "arjun@example.com",
        phone: "+91 10987 65432",
        role: "Student",
        department: "Mathematics",
        status: "Active",
    },
    {
        id: "10",
        name: "Divya Iyer",
        email: "divya@example.com",
        phone: "+91 99876 54321",
        role: "Teacher",
        department: "Science",
        status: "Inactive",
    },
    {
        id: "11",
        name: "Aditya Verma",
        email: "aditya@example.com",
        phone: "+91 88765 43210",
        role: "Student",
        department: "Physics",
        status: "Active",
    },
    {
        id: "12",
        name: "Neha Kapoor",
        email: "neha@example.com",
        phone: "+91 77654 32109",
        role: "Institute Admin",
        department: "Administration",
        status: "Active",
    },
    {
        id: "13",
        name: "Karthik Rao",
        email: "karthik@example.com",
        phone: "+91 66543 21098",
        role: "Student",
        department: "Chemistry",
        status: "Inactive",
    },
    {
        id: "14",
        name: "Meera Menon",
        email: "meera@example.com",
        phone: "+91 55432 10987",
        role: "Teacher",
        department: "English",
        status: "Active",
    },
    {
        id: "15",
        name: "Siddharth Pillai",
        email: "siddharth@example.com",
        phone: "+91 44321 09876",
        role: "Student",
        department: "Biology",
        status: "Active",
    },
];

export const userApi = {
    getUsers: async () => {
        return new Promise((resolve) => {
            setTimeout(() => resolve(MOCK_USERS), 300);
        });
    },
    getUserById: (id) => {
        return MOCK_USERS.find((user) => user.id === id) || null;
    },
};
